### PR TITLE
Fix "Invalid issuer address provided" issue #2

### PR DESCRIPTION
**Pull request by ProtonGustave**
Fix for #2

### CODE REVIEW

**Comment by sullof** [comment]
@ProtonGustave I think there is a simpler solution
https://github.com/TRON-US/tronweb/pull/8

Would you take a look and see if it works for you, please?
Thanks

**Comment by ProtonGustave** [comment]
@sullof it doesn't work for me because `issuerAddress` is `false` and `optional` param skip validating only for `null` or `undefined`.

**Comment by sullof** [comment]
You are right. I fixed that. Would you take a look, please?

**Comment by ProtonGustave** [comment]
It works for me now

**Comment by sullof** [comment]
Thanks.

**Pull request closed without merging**
